apiVersion: "pipeline.brainstorm.org/v1alpha1"
kind: Pipeline
metadata:
  name: camel-dataset-brainstorm
  namespace: default
spec:
  pipelineInfra:
    bootstrapServer: 'fuse-dev-02.tpb.lab.eng.brq.redhat.com'
    port: 9092
  sourceStep:
    image: quay.io/orpiske/camel-source-runner-01:latest
  transformationSteps:
    steps:
      - image: quay.io/orpiske/runner-transformer-step-01
      - image: quay.io/orpiske/runner-transformer-step-02
      - image: quay.io/orpiske/camel-transformer-step-03
  sinkStep:
    image: quay.io/orpiske/camel-sink-runner-01:latest