- route:
    id: route-3491
    from:
      id: from-3336
      description: start
      uri: timer:startTimer
      parameters:
        repeatCount: "1"
      steps:
        - setHeaders:
            id: setHeaders-1023
            headers:
              - expression:
                  constant:
                    expression: https://github.com/apache/camel/
                    resultType: java.lang.String
                name: REPOSITORY
              - expression:
                  constant:
                    expression: /opt/brainstorm/data/work/
                name: DATA_DIRECTORY
        - process:
            id: process-3518
            ref: checkProcessor
        - choice:
            id: choice-5626
            otherwise:
              id: otherwise-4184
              steps:
                - to:
                    uri: direct:pull
            when:
              - id: when-1797
                steps:
                  - to:
                      uri: direct:clone
                expression:
                  simple:
                    expression: ${header.exists} == false
        - process:
            id: process-5049
            ref: acquiredProcessor
        - marshal:
            id: marshal-2728
            json: {}
        - to:
            id: to-6168
            uri: direct:data.acquired
            parameters: {}
        - log:
            id: log-9711
            message: Data acquisition completed
- route:
    id: route-pull
    from:
      id: from-1634
      uri: direct:pull
      steps:
        - toD:
            id: toD-2378
            description: pull the repository
            uri: git:${header.DATA_DIRECTORY}/${header.name}
            parameters:
              allowEmpty: true
              branchName: main
              operation: pull
              remoteName: origin
- route:
    id: route-clone
    from:
      id: from-1634
      uri: direct:clone
      steps:
        - toD:
            id: toD-7686
            description: clone the repository
            uri: git:${header.DATA_DIRECTORY}/${header.name}
            parameters:
              allowEmpty: true
              branchName: main
              operation: clone
              remoteName: origin
              remotePath: ${header.REPOSITORY}
              targetBranchName: main
- beans:
    - name: checkProcessor
      type: org.brainstorm.camel.codefetcher.beans.CheckProcessor
    - name: acquiredProcessor
      type: org.brainstorm.camel.codefetcher.beans.AcquiredProcessor
