- route:
    id: route-8539
    from:
      id: from-3981
      uri: direct
      parameters:
        name: data-completed
      steps:
        - process:
            id: process-3358
            ref: publishProcessor
        - to:
            id: to-2167
            uri: direct
            parameters:
              name: end-of-pipeline
- beans:
    - name: publishProcessor
      type: org.brainstorm.camel.sink.beans.PublishProcessor
